version: "2.0"

services:
    pcobot-redis:
        image: redis:alpine
        volumes:
            - ./data/redis:/data
    pcobot:
        image: pastorhudson/pcobot:dev
        ports:
            - 4000:4000
        env_file:
            - default.env
        volumes:
            - ../plugins/pco:/opt/will/plugins/pco
            - ../will/templates:/opt/will/templates
            - ../will/backends:/opt/will/backends
            - ../will/mixins:/opt/will/mixins
            - ../will/plugins:/opt/will/plugins
            - ./config.py:/opt/will/config.py
        depends_on:
            - pcobot-redis
            
